name = "backend"
compatibility_date = "2024-07-25"

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWE1YTM2ODctN2U2Ni00Yzc3LWFjMDItYmM5N2M2YjQ0ODdkIiwidGVuYW50X2lkIjoiMjZhNWVkMWJmODRmMDc2M2EyNzQ4NzlmZDAwYWU0YTM2NmQzMTQ2MzQwOGQwNzYzNTk5ZWU4MzZjM2Q4NWIxYiIsImludGVybmFsX3NlY3JldCI6IjJkZjM0Nzg4LTY0ODQtNGFkMi04YTI3LTc1ODM5YjY4ZmE0NiJ9.EksD8JS72sgaqAOYNZ1vXuANNZqVv1FUTy6ZH88k1nA"